/**
 * Temporary passwords for new accounts and administrator resets.
 *
 * Generated by the server from the OS CSPRNG and shown ONCE to the
 * administrator, who passes it on. It is never stored in readable form, never
 * logged, never audited, and it stops working the moment the person chooses
 * their own password (mustChangePassword is set).
 *
 * The alphabet omits characters that are confused when read aloud or copied
 * by hand (0/O, 1/l/I), and the groups are separated by hyphens so it can be
 * dictated over the phone. 3 groups × 4 chars from 31 symbols ≈ 59 bits.
 */

import { randomInt } from 'node:crypto';

const ALPHABET = 'abcdefghjkmnpqrstuvwxyz23456789';

export function generateTemporaryPassword(groups = 3, groupLength = 4): string {
  return Array.from({ length: groups }, () =>
    Array.from({ length: groupLength }, () => ALPHABET[randomInt(ALPHABET.length)]).join(''),
  ).join('-');
}
